[project]
name = "sv"
version = "0.1.0"
uuid = "2y32up2m6bswq31lhbulra5qe"
description = "My awesome project"
license = "GPL-3.0-or-later"
keywords = ["cool", "swag"]
public = [
    "!*_tb.sv",
    "!noimport/",
]

[dependencies]
foo = "1.0"
bar = "2"