[[target]]
name = "foo"
description = "Print the blueprint contents"
plans = ["tsv", "json"]
fileset.text = "*.txt"
fileset.data = "*.dat"
command = "cat"
args = ["{{orbit.blueprint}}"]

[test]
default-target = "foo"

[build]
default-target = "foo"

[install]
default-protocol = "gitit"

[vhdl-format]
highlight-syntax = true

[verilog-format]
highlight-syntax = true


[[target]]
name = "multi"
command = "cat"
build = true
test = false
args = ["{{ orbit.blueprint }}"]
fileset.TEXT = { patterns = ["a.txt", "b.txt"] }

[[protocol]]
name = "gitit"
description = "Simple git protocol"
patterns = ["*.git"]
command = "git"
args = ["clone", "{{ orbit.ip.source }}"]

[[protocol]]
name = "bar"
command = "python"
args = ["bar.py"]
patterns = ["*.url"]

# [[target.fileset]]
# name = "FOO-SET"
# patterns = ["a.txt", "b.txt"]
# [[target.fileset]]
# name = "BAR-SET"
# patterns = ["x.y"]