[env]
LICENSE_FILE = { value = "3000@server", force = true }

[[target]]
name = "foo"
description = "Print the blueprint contents"
plans = ["tsv", "json"]
fileset.text = "*.txt"
fileset.data = "*.dat"
command = ["cat", "{{ orbit.blueprint }}"]

[test]
target = "foo"

[build]
target = "foo"

[install]
protocol = "gitit"

[vhdl-format]
highlight-syntax = true

[verilog-format]
highlight-syntax = true

[[target]]
name = "gui"
description = "Set up an interactive ongoing process"
command = ["python", "gui.py"]

[[target]]
name = "tui"
description = "Set up an interactive ongoing process"
command = ["python", "gui.py"]

[[target]]
name = "multi"
command = ["cat", "{{ orbit.blueprint }}"]
build = true
test = false
fileset.TEXT = { patterns = ["a.txt", "b.txt"] }

[[protocol]]
name = "gitit"
description = "Simple git protocol"
patterns = ["*.git"]
command = ["git", "clone", "{{ orbit.project.source }}"]

[[protocol]]
name = "bar"
command = ["python", "bar.py"]
patterns = ["*.url"]

# [[target.fileset]]
# name = "FOO-SET"
# patterns = ["a.txt", "b.txt"]
# [[target.fileset]]
# name = "BAR-SET"
# patterns = ["x.y"]