[project]
name = "vhdl-examples"
uuid = "ecj831jmc018hhhgl1d4rzgw8"
version = "0.0.9"
public = ["adder.vhd"]
channels = ["hyperspace-labs"]

[dependencies]
# gates = "2"
# b = { version = "0.1.0", path = "../b" }
# serdes = { version = "1.0.0", uuid = "" }