#!/usr/bin/env bash

# A packaging script for CICD.
# Reference: https://github.com/casey/just/blob/master/bin/package

set -euxo pipefail

VERSION=$VERSION
DIST=`pwd`/dist

echo "Packaging orbit $VERSION for $TARGET..."

test -f Cargo.lock || cargo generate-lockfile

echo "Installing rust toolchain for $TARGET..."
rustup target add $TARGET

if [[ $TARGET == aarch64-unknown-linux-musl ]]; then
  export CC=aarch64-linux-gnu-gcc
fi

if [ $TARGET == armv7-unknown-linux-musleabihf ] || [ $TARGET == arm-unknown-linux-musleabihf ]; then
    export REALGCC=arm-linux-gnueabihf-gcc
    export TARGET_CC=musl-gcc
fi

echo "Building orbit docs..."
# inject current version of Orbit into the "Installing" page
python ./tools/sync_docs_version.py ./docs/src/starting/installing.md
mdbook build docs

echo "Building orbit installer..."
RUSTFLAGS="--deny warnings --codegen target-feature=+crt-static $TARGET_RUSTFLAGS" \
  cargo build --bin install --target $TARGET --release
INSTALLER=target/$TARGET/release/install

echo "Building orbit..."
RUSTFLAGS="--deny warnings --codegen target-feature=+crt-static $TARGET_RUSTFLAGS" \
  cargo build --bin orbit --target $TARGET --release
EXECUTABLE=target/$TARGET/release/orbit

if [[ $OS == windows-latest ]]; then
  EXECUTABLE=$EXECUTABLE.exe
  INSTALLER=$INSTALLER.exe
fi

echo "Copying release files..."

# Copy supportive/miscellaneous files
mkdir $DIST
cp -r \
  $INSTALLER \
  Cargo.lock \
  Cargo.toml \
  LICENSE \
  docs/pack/README.txt \
  $DIST

# Copy the generated docs
mkdir $DIST/docs
cp -r \
  docs/book/* \
  $DIST/docs

# Copy the binary
mkdir $DIST/bin
cp \
  $EXECUTABLE \
  $DIST/bin

cd $DIST
echo "Creating release archive..."
case $OS in
  ubuntu-latest | macos-latest)
    ARCHIVE=orbit-$VERSION-$TARGET.tar.gz
    tar czf $ARCHIVE *
    echo "archive=$DIST/$ARCHIVE" >> $GITHUB_OUTPUT
    ;;
  windows-latest)
    ARCHIVE=orbit-$VERSION-$TARGET.zip
    7z a -r $ARCHIVE *
    echo "archive=`pwd -W`/$ARCHIVE" >> $GITHUB_OUTPUT
    ;;
esac