[book]
title = "The Orbit Book"
authors = ["Chase Ruskin"]
language = "en"
src = "src"

[build]
create-missing = false

[output.html]
smart-punctuation = true
definition-lists = true
admonitions = true
theme = "./theme"
no-section-label = false
git-repository-url = "https://github.com/chaseruskin/orbit"
git-repository-icon = "fab-github"
sidebar-header-nav = false