name: Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tools:
    uses: ./.github/workflows/tools.yml

  check-release:
    uses: ./.github/workflows/check-release.yml
    needs: [tools]

  test:
    uses: ./.github/workflows/test.yml

  bazel:
    uses: ./.github/workflows/bazel.yml

  build:
    uses: ./.github/workflows/build.yml
    needs: [tools, check-release, test]
    with:
      is_release: ${{ needs.check-release.outputs.ready }}

  integrity:
    uses: ./.github/workflows/integrity.yml
    needs: [tools, build]

  system-test:
    uses: ./.github/workflows/system-test.yml
    needs: [check-release, integrity]
    with:
      version: ${{ needs.check-release.outputs.version }}

  docker-build:
    uses: ./.github/workflows/docker.yml
    needs: [check-release, system-test]
    if: ${{ github.ref == 'refs/heads/trunk' }}
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    with:
      version: ${{ needs.check-release.outputs.version }}
      is_release: ${{ needs.check-release.outputs.ready }}

  release:
    uses: ./.github/workflows/release.yml
    if: ${{ needs.check-release.outputs.ready == '1' && github.ref == 'refs/heads/trunk' }}
    needs: [check-release, system-test, docker-build]
    with:
      version: ${{ needs.check-release.outputs.version }}
